version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/watch-rails
    environment:
      RAILS_ENV: development

  database:
    image: postgres:latest
    volumes:
      - .db_data:/var/lib/postgresql/data