version: 2.1

jobs:
    build:
        - image: "docker/compose:latest"
    steps:
        - checkout
        - run:
            name: build docker image
            command: docker-compose up -d --build
            command: docker-compose exec app bundle exec rake db:setup db:migrate
    Exit:
        steps:
            - run:
                name: Exit
                command: docker-compose logs
                command: docker-compose down
